title: YU Chunxue
logo: /assets/img/headshot_circle.png
description: Here is Snowy (喻春雪). I am pursuing my doctoral degree in Computational Social Science at The Chinese University of Hong Kong, Shenzhen. Happy to engage in academic conversations! My email is 224030231@link.cuhk.edu.cn.
show_downloads: false
theme: jekyll-theme-minimal
