title: YU Chunxue
logo: /assets/img/headshot_circle.png
description: Happy to engage in academic conversations! My email is 224030231@link.cuhk.edu.cn.
show_downloads: false
theme: jekyll-theme-minimal
